### ISSUE TITLE
Missing Jackson module for handling Java 8 date/time types

### ISSUE THREAD

**Issue by cberg-zalando** [zalando/zally#1285]
I am not sure if the dependency bumps in #920 caused the failure, but in one of our repositories `zally` (see [CDP build](https://sunrise.zalando.net/cdp/ghe/broadway/macao/l-2jip6j34b9xybq6s7rbz3au9qr/steps/0/logs)) started failing this morning with an error, saying that `Java 8 date/time type `java.time.OffsetDateTime` not supported by default`.

So either the dependency `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` was accidentally removed or the module is for whatever reason not registered with Jackson anymore.

**Comment by tkrop** [comment]
Log excerpt:

```
2021-07-08 07:27:51.053 ERROR 9 --- [nio-8080-exec-7] o.z.p.spring.web.advice.AdviceTrait      : Internal Server Error

java.lang.RuntimeException: check invocation failed: id=176 title=Use Problem JSON checkName=validate reason=java.lang.IllegalArgumentException: Java 8 date/time type `java.time.OffsetDateTi
me` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: io.swagger.v3.oas.models.media.Schema["properti
es"]->java.util.LinkedHashMap["images"]->io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["header"]->io.swagger.v3.oas.models.media.Schema["properties"]->ja
va.util.LinkedHashMap["created_at"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])
        at org.zalando.zally.core.RulesValidator.invoke(RulesValidator.kt:63) ~[zally-core-2.0.1-SNAPSHOT.jar!/:na]
        at org.zalando.zally.core.RulesValidator.validate(RulesValidator.kt:40) ~[zally-core-2.0.1-SNAPSHOT.jar!/:na]
        at org.zalando.zally.core.CompositeRulesValidator.validate(CompositeRulesValidator.kt:9) ~[zally-core-2.0.1-SNAPSHOT.jar!/:na]
        at org.zalando.zally.apireview.ApiViolationsController.validate(ApiViolationsController.kt:47) ~[classes!/:na]
...
Caused by: java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor512.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.zalando.zally.core.RulesValidator.invoke(RulesValidator.kt:61) ~[zally-core-2.0.1-SNAPSHOT.jar!/:na]
        ... 94 common frames omitted
Caused by: java.lang.IllegalArgumentException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" 
to enable handling (through reference chain: io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["images"]->io.swagger.v3.oas.models.media.ObjectSchema["properties"]
->java.util.LinkedHashMap["header"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["created_at"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4314) ~[jackson-databind-2.12.2.jar!/:2.12.2]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4245) ~[jackson-databind-2.12.2.jar!/:2.12.2]
        at org.zalando.zally.ruleset.zalando.UseProblemJsonRule.testForProblemSchema(UseProblemJsonRule.kt:68) ~[zally-ruleset-zalando-2.0.1-SNAPSHOT.jar!/:na]
        at org.zalando.zally.ruleset.zalando.UseProblemJsonRule.validate(UseProblemJsonRule.kt:46) ~[zally-ruleset-zalando-2.0.1-SNAPSHOT.jar!/:na]
        ... 98 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["images"]->io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["header"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["created_at"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[jackson-databind-2.12.2.jar!/:2.12.2]
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276) ~[jackson-databind-2.12.2.jar!/:2.12.2]
...
```
```

**Comment by cberg-zalando** [comment]
See the actual API definition triggering the error: https://github.bus.zalan.do/broadway/macao/blob/master/api/macao-api.yaml#L758

**Comment by vadeg** [comment]
property example
```
created_at:
type: string
format: date-time
example: '2020-05-14T14:22:01Z'
```

**Comment by vadeg** [comment]
The dependency is in place.
