### ISSUE TITLE
zally doesn't start - Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.

### ISSUE THREAD

**Issue by dirkgomez** [zalando/zally#683]
My local zally checkout is at 079dc7d34670d8cad810480719c5dc37ef001625 and I am starting it with: ./build-and-run.sh 

The browser just shows a white page and the console fails wit

`SyntaxError: expected expression, got '<' `

Here's the probable cause:

`server_1    | java.lang.reflect.InvocationTargetException: null`
`....`
`server_1    | Caused by: java.sql.SQLFeatureNotSupportedException: Method ``org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.`
`server_1    | 	at org.postgresql.Driver.notImplemented(Driver.java:683) ~[postgresql-42.2.1.jar!/:42.2.1]`
`server_1    | 	at org.postgresql.jdbc.PgConnection.createClob(PgConnection.java:1252)` `~[postgresql-42.2.1.jar!/:42.2.1]`

**Comment by roxspring** [comment]
I think you're wrong about the probable cause - I see the same in our server which is running happily. 

Are there other error messages further down the log?

**Comment by dirkgomez** [comment]
Don't know.

Here's the result of `wget localhost:8080`:

<html><head><meta charset="utf-8"/><title>Zally API Linter WEB UI</title><base href="/"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link href="https://fonts.googleapis.com/css?family=Ubuntu:300,500,300italic|Ubuntu+Mono" rel="stylesheet" type="text/css"/><link href="https://unpkg.com/dress-code@2.3.0/dist/css/dress-code.min.css" rel="stylesheet" type="text/css"/><link rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/icons/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/icons/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon-precomposed" sizes="120x120" href="/assets/icons/apple-touch-icon-120x120.png"/><link rel="apple-touch-icon-precomposed" sizes="152x152" href="/assets/icons/apple-touch-icon-152x152.png"/><link rel="icon" type="image/png" href="/assets/icons/favicon-32x32.png" sizes="32x32"/><link rel="icon" type="image/png" href="/assets/icons/favicon-16x16.png" sizes="16x16"/><meta name="application-name" content="&amp;nbsp;"/><meta name="msapplication-TileColor" content="#FFFFFF"/><meta name="msapplication-TileImage" content="mstile-144x144.png"/><script src="/env.js" type="text/javascript"></script></head><body><div id="app"></div><script src="/assets/bundle.js" type="text/javascript"></script></body></html>

**Comment by dirkgomez** [comment]
How can I raise the debug level?

**Comment by maxim-tschumak** [comment]
```
Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
```
This is "OK": It happens since the migration to Spring Boot 2 and doesn't cause the server to really fail. I believer Spring Boot guys have to fix this.


> How can I raise the debug level?

You can change the `window.env.DEBUG` variable to `true`. (https://github.com/zalando/zally/blob/1b97fa0c0903a8cf2a0f514aa9d203c5b9aeffde/web-ui/src/client/app/services/debug.js#L2)

> Here's the result of wget localhost:8080:
  <title>Zally API Linter WEB UI</title><script src="/env.js" type="text/javascript"></script> 
  <script src="/assets/bundle.js" type="text/javascript"></script>

I cannot reproduce this. Please provide us your configuration (OS, docker, docker-compose versions, etc) and more log output. It will help us to reconstruct your issue.

**Comment by dirkgomez** [comment]
How do I set `window.env.DEBUG` to `true`? I just removed the if statement in debug.js, but there was no good output in the browser console.

What I can tell you now is: bundle.js contains html: 
`<html><head><meta charset="utf-8"/><title>Zally API Linter WEB UI</title><base href="/"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link href="https://fonts.googleapis.com/css?family=Ubuntu:300,500,300italic|Ubuntu+Mono" rel="stylesheet" type="text/css"/><link href="https://unpkg.com/dress-code@2.3.0/dist/css/dress-code.min.css" rel="stylesheet" type="text/css"/><link rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/icons/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/icons/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon-precomposed" sizes="120x120" href="/assets/icons/apple-touch-icon-120x120.png"/><link rel="apple-touch-icon-precomposed" sizes="152x152" href="/assets/icons/apple-touch-icon-152x152.png"/><link rel="icon" type="image/png" href="/assets/icons/favicon-32x32.png" sizes="32x32"/><link rel="icon" type="image/png" href="/assets/icons/favicon-16x16.png" sizes="16x16"/><meta name="application-name" content="&amp;nbsp;"/><meta name="msapplication-TileColor" content="#FFFFFF"/><meta name="msapplication-TileImage" content="mstile-144x144.png"/><script src="/env.js" type="text/javascript"></script></head><body><div id="app"></div><script src="/assets/bundle.js" type="text/javascript"></script></body></html>`

My configuration:

uname -a
Darwin MacBookPro-5GTFM 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

docker -v
Docker version 17.12.0-ce, build c97c6d6

docker-compose -v
docker-compose version 1.18.0, build 8dd22a9

**Comment by maxim-tschumak** [comment]
@dirkgomez You probably starting docker-compose without building the sources. We have s script which builds Zally Server and  Zally Web-UI and starts docker-compose then:
```
./build-and-run.sh
```
Please try this.

**Comment by dirkgomez** [comment]
@maxim-tschumak I just wanted to skip the tests, but the build-and-run.sh script exhibits the same behaviour. See attached logfile.

I am also attaching the network analysis tab of my browser, maybe something fishy is obvious from there?

[zally-start.log](https://github.com/zalando/zally/files/1818550/zally-start.log)

<img width="1176" alt="zally-localhost8080" src="https://user-images.githubusercontent.com/76068/37511952-edd9f232-2900-11e8-9493-b9ec07a32fdb.png">

**Comment by maxim-tschumak** [comment]
```
./build-and-run.sh: line 18: yarn: command not found
```
This is probably the problem. Please install `yarn` (https://yarnpkg.com/lang/en/docs/install/)

**Comment by dirkgomez** [comment]
Thanks a lot, it works now. 

Please have a look at my pull request!

**Comment by netme** [comment]
Looks like the issue is resolved. Closing.

**Comment by avaradan** [comment]
Hi, I am having same issue in web UI rendering. I setup the project recently and ran ./build-and-run.sh but UI shows nothing. Can someone pls help me? 

![image](https://user-images.githubusercontent.com/8282477/54103665-44afda00-43f3-11e9-8bb8-181a075dcc79.png)

Attaching the startup log below. 
[zally.log](https://github.com/zalando/zally/files/2950864/zally.log)

wget command has no issues. 
aravindanvaradan@Arvindan3150161:~/zally/zally-master/web-ui$ wget localhost:8080
--2019-03-11 11:40:35--  http://localhost:8080/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1548 (1.5K) [text/html]
Saving to: ‘index.html’

index.html                    100%[=================================================>]   1.51K  --.-KB/s    in 0s

2019-03-11 11:40:35 (155 MB/s) - ‘index.html’ saved [1548/1548]

**Comment by thuemmler-zeppelin** [comment]
Even if this is closed - i would like to point out that with a recent install fresh from the repo it re-occurs. Any hint on this one? I can not see any errors in the logs during the whole build process and so on. And the result is the exact same: There is html (probably delivered by the server) inside bundle.js.
