### ISSUE TITLE
TargetInvocationException: null

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/zally#787]
# How to reproduce

Lint this API in Zally.

```yaml
swagger: "2.0"
info:
  x-audience: business-unit-internal
  x-api-id: d0184f38-b98d-11e7-9c56-68f728c1ba70
  title: foo
  description: bar
  version: 1.0.0
  contact:
    email: a@b.c
    name: James Bond
    url: https://www.mi6.co.gov
securityDefinitions:
  oauth2:
    type: oauth2
    flow: application
    tokenUrl: https://identity.example.com/oauth2/token
    scopes:
      lalala.read: Access right needed to read
      lalala.write: Access right needed to write
paths: 
  /foos/bars:
    get:
      description: asd
```

The front end will answer:

> ERROR
> Ooops something went wrong!

The server will log:
```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at de.zalando.zally.rule.RulesValidator.invoke(RulesValidator.kt:60) ~[main/:na]
...
Caused by: java.lang.NullPointerException: null
	at de.zalando.zally.rule.zalando.Use429HeaderForRateLimitRule.checkHeadersForRateLimiting(Use429HeaderForRateLimitRule.kt:22) ~[classes!/:na]

```

**Comment by roxspring** [comment]
Still reproduces on master.

**Comment by tkrop** [comment]
Added error detail from live server:
```
Caused by: java.lang.NullPointerException: null
	at de.zalando.zally.rule.zalando.Use429HeaderForRateLimitRule.checkHeadersForRateLimiting(Use429HeaderForRateLimitRule.kt:22) ~[classes!/:na]
```
