### ISSUE TITLE
Checking recursive APIs schemas result in StackOverflowException

### ISSUE THREAD

**Issue by tkrop** [zalando/zally#826]
Example: https://github.bus.zalan.do/setanta/api-reviews/pull/1/files

**Comment by tkrop** [comment]
Stack is something like:
```
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at de.zalando.zally.rule.RulesValidator.invoke(RulesValidator.kt:60) ~[classes!/:na]
        at de.zalando.zally.rule.RulesValidator.validate(RulesValidator.kt:40) ~[classes!/:na]
        at de.zalando.zally.rule.CompositeRulesValidator.validate(CompositeRulesValidator.kt:14) ~[classes!/:na]
        at de.zalando.zally.apireview.ApiViolationsController.validate(ApiViolationsController.kt:42) ~[classes!/:na]
...
Caused by: java.lang.StackOverflowError: null
        at io.swagger.v3.oas.models.media.StringSchema.hashCode(StringSchema.java:95) ~[swagger-models-2.0.3.jar!/:2.0.3]
        at java.util.Objects.hashCode(Objects.java:98) ~[na:1.8.0_171]
        at java.util.HashMap$Node.hashCode(HashMap.java:297) ~[na:1.8.0_171]
        at java.util.AbstractMap.hashCode(AbstractMap.java:530) ~[na:1.8.0_171]
        at java.util.Arrays.hashCode(Arrays.java:4146) ~[na:1.8.0_171]
        at java.util.Objects.hash(Objects.java:128) ~[na:1.8.0_171]
        at io.swagger.v3.oas.models.media.Schema.hashCode(Schema.java:795) ~[swagger-models-2.0.3.jar!/:2.0.3]
        at java.util.Arrays.hashCode(Arrays.java:4146) ~[na:1.8.0_171]
        at java.util.Objects.hash(Objects.java:128) ~[na:1.8.0_171]
        at io.swagger.v3.oas.models.media.ArraySchema.hashCode(ArraySchema.java:83) ~[swagger-models-2.0.3.jar!/:2.0.3]
```
